# Generated by Django 6.0.4 on 2026-05-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='polls/covers/'),
        ),
    ]
